apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: demo
  labels:
    app: minio
spec:
  replicas: 1
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          args:
          - minio server /data --console-address :9090
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "1500Mi"
              cpu: "1500m"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
        claimName: efs-claim
        path: /mnt/disk1/data
        type: DirectoryOrCreate 
      restartPolicy: Always    
  selector:
    matchLabels:
      app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: demo
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      name: console
    - port: 9000
      name: s3
  type: ClusterIP
