--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: test-volume
spec: 
  accessModes: 
    - ReadWriteOnce
  awsElasticBlockStore: 
    fsType: xfs
    volumeID: vol-05f0247137404ffaf
  capacity: 
    storage: 20Gi
  storageClassName: standard
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: standard
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: test-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 200Gi
  storageClassName: standard
