apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: efs-volume
      mountPath: /data
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: efs-pvc
